### ISSUE TITLE
Unable to get timeline to display properly

### ISSUE THREAD

**Issue by JordanMPDS** [SimplGy/jekyll-timeline#4]
I have my own jekyll site and wanted to add this timeline functionally to it.  I'm on Jekyll 4.3.2 and I added the jekyll-timeline.html, jekyll-timeline.css, and jekyll-timeline-li-event.html to my _includes folder.  I tried to recreate the example-minimal and the screenshot below is what I see after creating it.

![image](https://github.com/SimplGy/jekyll-timeline/assets/151422739/6fb19a9f-bc8b-4f92-9ad6-94fc349d84f1)

I'm not a web dev and this is my first time using jekyll so please let me know if I set it up wrong or if i'm missing something.

**Comment by JordanMPDS** [comment]
Was successfully able to update it myself to work with jekyll 4.3.2

**Comment by SimplGy** [comment]
Thanks for persisting with this, and sorry I wasn't really paying attention to github issues. Didn't know anyone used this thing :)

Sounds like an issue with Jekyll having upgraded.

**Comment by JordanMPDS** [comment]
Yep had to make some changes to the gem files and I was able to get it working.  Not a swe and first time using jekyll/ruby so learning everything as i go.
